"""Add is_rejected to ExchangeRequest

Revision ID: 957782ff2586
Revises: fe575aafe71c
Create Date: 2025-05-15 03:05:28.140914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957782ff2586'
down_revision = 'fe575aafe71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_request', schema=None) as batch_op:
        batch_op.drop_column('is_rejected')

    # ### end Alembic commands ###
